import { describe, it, expect } from 'vitest'
import { createRng } from '../../src/sim/rng.js'

describe('createRng', () => {
  it('produces identical sequences for identical seeds', () => {
    const a = createRng(12345)
    const b = createRng(12345)
    const seqA = Array.from({ length: 100 }, () => a())
    const seqB = Array.from({ length: 100 }, () => b())
    expect(seqA).toEqual(seqB)
  })

  it('produces different sequences for different seeds', () => {
    const a = createRng(1)
    const b = createRng(2)
    expect(Array.from({ length: 10 }, () => a())).not.toEqual(
      Array.from({ length: 10 }, () => b()),
    )
  })

  it('stays within [0, 1)', () => {
    const r = createRng(99)
    for (let i = 0; i < 10_000; i++) {
      const v = r()
      expect(v).toBeGreaterThanOrEqual(0)
      expect(v).toBeLessThan(1)
    }
  })

  /**
   * Spec §3: transcendentals vary across V8 versions; integer ops do not.
   *
   * Finding M7: this test's comment promised "these values were generated by
   * this implementation and must never drift" but committed no values -- it
   * only asserted that two fresh generators agreed with each other in the
   * same process, which is true of any deterministic function of the seed,
   * including a rewritten mixing function. The actual numbers are committed
   * now, so a refactor of mulberry32's mixing steps is caught.
   *
   * Generated 2026-09-12 by this implementation on node v22.22.1. A change
   * here is either a bug in `createRng` or a deliberate re-seeding of every
   * recorded artefact that depends on it (the soak's counters, most
   * immediately) -- not a number to update casually.
   */
  it('is bit-exact: the committed first three draws from seed 42', () => {
    const r = createRng(42)
    expect([r(), r(), r()]).toEqual([
      0.6011037519201636,
      0.44829055899754167,
      0.8524657934904099,
    ])
  })

  it('re-derives the same sequence from a fresh generator', () => {
    const r = createRng(42)
    const first = [r(), r(), r()]
    const again = createRng(42)
    expect([again(), again(), again()]).toEqual(first)
  })
})
