import { statSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { createRng } from '../../src/sim/rng.js'
import { readWav, writeWav } from './wav.js'

/**
 * A PLACEHOLDER `rocket_whoosh.wav`, generated purely in code because Mark
 * has not yet supplied a real Firefly-recorded one (Plan 6b Task 10; see
 * `content/audio/NOTICE.md` and `ASSETS.md`).
 *
 * `bombs_away.wav` and the five other clips in `content/audio/` are real
 * Adobe Firefly recordings whose provenance is a dated author statement plus
 * a C2PA manifest -- neither of which a code-generated file can have or
 * needs. `ASSETS.md`'s own precedent for that is the terrain/weathering
 * textures in `src/render/terrain/surface.ts`: "Original... generated by
 * [a script], authored for this project, AGPL-3.0-or-later." This script is
 * that precedent applied to audio: deterministic, no external samples, no
 * license to misattribute. Swap this file for a real recording later by
 * dropping a new `content/audio/rocket_whoosh.wav` in place and re-measuring
 * `bytes`/`peakFullScale` in `src/audio/assets.ts` -- no code changes needed
 * on the cue or playback side either way.
 *
 * Shape: a short rushing-air burst, not a recorded rocket motor. Per-channel
 * white noise (mulberry32, seeded, so the file is byte-reproducible) run
 * through a one-pole low-pass to round off the hiss into something closer to
 * airflow than static, under an attack/decay amplitude envelope -- a quick
 * 30 ms rise to peak as the motor lights, then a nine-times-longer decay as
 * the rocket pulls away down the gunsight line. Two independently-seeded
 * channels give it a stereo width the six Firefly clips already have.
 */

const SAMPLE_RATE = 48_000
const CHANNELS = 2
const DURATION_S = 0.5
const FRAMES = Math.round(SAMPLE_RATE * DURATION_S)
const ATTACK_S = 0.03
const LOWPASS_ALPHA = 0.12 // one-pole filter coefficient: lower = duller/airier
const TARGET_PEAK = 0.85 // full-scale headroom target before measuring the real one

function envelope(tS: number): number {
  if (tS < ATTACK_S) return tS / ATTACK_S
  const decayS = DURATION_S - ATTACK_S
  const tau = decayS / 3 // ~3 time constants over the tail, audibly to near-zero
  return Math.exp(-(tS - ATTACK_S) / tau)
}

function synthesizeChannel(seed: number): Float64Array {
  const rng = createRng(seed)
  const out = new Float64Array(FRAMES)
  let filtered = 0
  for (let i = 0; i < FRAMES; i++) {
    const white = rng() * 2 - 1
    filtered += LOWPASS_ALPHA * (white - filtered)
    out[i] = filtered * envelope(i / SAMPLE_RATE)
  }
  return out
}

function synthesize(): Int16Array {
  const channels = Array.from({ length: CHANNELS }, (_, c) => synthesizeChannel(0x1a1e5501 + c))
  let peak = 0
  for (const ch of channels) for (const s of ch) peak = Math.max(peak, Math.abs(s))
  const scale = peak > 0 ? TARGET_PEAK / peak : 0
  const interleaved = new Int16Array(FRAMES * CHANNELS)
  for (let i = 0; i < FRAMES; i++) {
    for (let c = 0; c < CHANNELS; c++) {
      const v = Math.max(-1, Math.min(1, channels[c]![i]! * scale))
      interleaved[i * CHANNELS + c] = Math.round(v * 32767)
    }
  }
  return interleaved
}

const outPath = fileURLToPath(new URL('../../content/audio/rocket_whoosh.wav', import.meta.url))
writeWav(outPath, synthesize(), SAMPLE_RATE, CHANNELS)

const bytes = statSync(outPath).size
const { samples } = readWav(outPath)
let measuredPeak = 0
for (const s of samples) measuredPeak = Math.max(measuredPeak, Math.abs(s))
console.log(`wrote ${outPath}`)
console.log(`bytes: ${bytes}`)
console.log(`peakFullScale: ${(measuredPeak / 32768).toFixed(4)}`)
